package ai.cookwala.samples;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The bundled snapshot: envelopes, heat bands, limits, four recipes, four devices and the expected answers.
 *
 * <p>The file is {@code samples/data/bundle.json} in the Cookwala repository, put on the classpath at
 * {@code ai/cookwala/samples/bundle.json} by the build. It is regenerated by samples/tools/build_bundle.py and never
 * edited by hand. The parsed document is shared: treat it as read-only (use {@link Json#copy} before changing anything).
 */
public final class Bundle {
    private Bundle() {}

    private static volatile Map<String, Object> cached;

    /** The whole bundle, parsed once. */
    public static Map<String, Object> load() {
        Map<String, Object> b = cached;
        if (b == null) {
            synchronized (Bundle.class) {
                if (cached == null) {
                    try (InputStream in = Bundle.class.getResourceAsStream("bundle.json")) {
                        if (in == null) throw new IllegalStateException("ai/cookwala/samples/bundle.json is not on the classpath");
                        cached = Json.parseObject(new String(in.readAllBytes(), StandardCharsets.UTF_8));
                    } catch (IOException e) {
                        throw new UncheckedIOException(e);
                    }
                }
                b = cached;
            }
        }
        return b;
    }

    public static Map<String, Object> ops() { return Py.obj(load(), "ops"); }
    public static Map<String, Object> heatBands() { return Py.obj(load(), "heatBands"); }
    public static Map<String, Object> safetyLimits() { return Py.obj(load(), "safetyLimits"); }
    public static Map<String, Object> recipes() { return Py.obj(load(), "recipes"); }
    public static Map<String, Object> devices() { return Py.obj(load(), "devices"); }
    public static Map<String, Object> expected() { return Py.obj(load(), "expected"); }
    public static String now() { return (String) load().get("now"); }
    public static String core() { return (String) load().get("core"); }

    public static Map<String, Object> recipe(String key) { return Py.asMap(recipes().get(key)); }
    public static Map<String, Object> device(String key) { return Py.asMap(devices().get(key)); }

    /** Find a recipe by global reference (cw:cookwala.ai:example-shakshuka), document id or bundle key. */
    public static Map<String, Object> recipeByRef(Map<String, Object> recipes, String gref) {
        String[] colon = gref.split(":", -1);
        String[] hash = colon[colon.length - 1].split("#", -1);
        String rid = hash[hash.length - 1];
        for (Map.Entry<String, Object> e : recipes.entrySet()) {
            Map<String, Object> doc = Py.asMap(e.getValue());
            if (doc == null) continue;
            if (rid.equals(e.getKey()) || rid.equals(doc.get("id"))) return doc;
        }
        return null;
    }

    /** cw:cookwala.ai:&lt;id&gt; */
    public static String globalRef(Map<String, Object> recipe) {
        return "cw:cookwala.ai:" + recipe.get("id");
    }

    /** Every allergen the recipe declares, in any scheme, plus per-ingredient allergens. */
    public static Set<String> recipeAllergens(Map<String, Object> recipe) {
        Set<String> present = new HashSet<>();
        if (recipe == null) return present;
        Object declared = Py.obj(recipe, "safety").get("allergens");
        if (declared instanceof Map) {
            for (Object lst : ((Map<?, ?>) declared).values()) if (lst instanceof List) addAll(present, (List<?>) lst);
        } else if (declared instanceof List) {
            addAll(present, (List<?>) declared);
        }
        for (Object ing : Py.arr(recipe, "ingredients")) {
            Map<String, Object> m = Py.asMap(ing);
            if (m != null) addAll(present, Py.arr(m, "allergens"));
        }
        return present;
    }

    private static void addAll(Set<String> out, List<?> l) {
        for (Object o : l) out.add(Py.pyStr(o));
    }
}
