// Calibrates the country model from the city simulator (multi-scale modelling).
// Runs the city engine for urban / suburban / rural archetypes × robot share × protocol on/off,
// averages two seeds, and writes per-person-per-day unit rates to calibration.js.
// Usage: node sim/country/calibrate.mjs
import { writeFileSync } from 'node:fs';
import { simulateCities } from '../city/engine.js';

export const ARCHETYPES = {
  urban: { label: 'Urban', distKm: 0.8, farmKm: 60, wholesaleKm: 6 },
  suburban: { label: 'Suburban', distKm: 3.0, farmKm: 40, wholesaleKm: 12 },
  rural: { label: 'Rural', distKm: 8.0, farmKm: 15, wholesaleKm: 25 }
};
const SHARES = [0, 0.25, 0.5, 0.75, 1];
const SEEDS = [11, 29];
const METRICS = ['householdWaste', 'inedibleWaste', 'farmLoss', 'wholesaleDiscard', 'retailDiscard', 'packaging', 'garbage', 'carKm', 'vanKm', 'truckKm', 'garbageKm', 'foodVkm',
  'fuelL', 'gasM3', 'gasKwh', 'cookElecKwh', 'robotKwh', 'coldKwh', 'energyKwh', 'co2', 'wasteCo2', 'spend', 'rescued', 'mealsRescued', 'humanHours', 'stockouts', 'attempts', 'deliveries'];

function cityFor(arch, share, eco) {
  const a = ARCHETYPES[arch];
  return {
    id: 'A', name: `${a.label} ${share} ${eco}`, demandSignals: eco, consolidated: eco, rescue: eco, bulkPackaging: eco, energySaver: eco,
    stoveMix: { gas: 0.55, electric: 0.35, induction: 0.1 },
    communities: [0, 1, 2].map((i) => ({ id: `C${i}`, name: `C${i}`, homes: 500, income: ['low', 'mid', 'high'][i], distKm: a.distKm, robotShare: share })),
    roadCapacity: 9600, backgroundVkmPeak: 8600, farmKm: a.farmKm, wholesaleKm: a.wholesaleKm
  };
}

const rates = {};
for (const arch of Object.keys(ARCHETYPES)) {
  rates[arch] = { eco: [], noEco: [] };
  for (const eco of [true, false]) {
    for (const share of SHARES) {
      const acc = Object.fromEntries(METRICS.map((k) => [k, 0]));
      let homes = 0;
      for (const seed of SEEDS) {
        const r = simulateCities({ seed, days: 30, cities: [cityFor(arch, share, eco)] });
        const c = r.cities[0];
        const pd = c.people * r.days;
        for (const k of METRICS) acc[k] += (c.totals[k] || 0) / pd / SEEDS.length;
        homes += c.homes / c.people / SEEDS.length;
      }
      acc.homesPerPerson = homes;
      rates[arch][eco ? 'eco' : 'noEco'].push({ share, ...Object.fromEntries(Object.entries(acc).map(([k, v]) => [k, Number(v.toPrecision(5))])) });
      process.stdout.write(`${arch} eco=${eco} share=${share} waste ${acc.householdWaste.toFixed(3)} energy ${acc.energyKwh.toFixed(3)}\n`);
    }
  }
}
const src = `// Generated by sim/country/calibrate.mjs from the city simulator. Do not edit by hand.\n// Per-person-per-day unit rates by archetype × protocol (eco) × robot share.\nexport const SHARES = ${JSON.stringify(SHARES)};\nexport const CALIBRATION = ${JSON.stringify(rates)};\n`;
writeFileSync(new URL('./calibration.js', import.meta.url), src);
console.log('wrote sim/country/calibration.js');
