#!/usr/bin/env python3
"""Self-host the site's web fonts (SIL Open Font License) so pages make no request to Google.

Downloads the woff2 files Google Fonts would serve for the latin and arabic stylesheets and
writes site/assets/fonts/{latin,arabic}.css with local URLs. Run when the font list changes.
"""
import re, sys, urllib.request, hashlib, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / 'site' / 'assets' / 'fonts'
UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0 Safari/537.36'
SETS = {
    'latin': 'https://fonts.googleapis.com/css2?family=Geist:wght@300;400;500;600&family=Geist+Mono:wght@400;500&family=Fraunces:wght@600&display=swap',
    'arabic': 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;500;600&family=Geist+Mono:wght@400;500&family=Fraunces:wght@600&display=swap',
}
def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA}), timeout=60).read()
def main():
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    for name, url in SETS.items():
        css = get(url).decode()
        def repl(m):
            nonlocal total
            u = m.group(1)
            fam = re.search(r'/s/([a-z]+)/', u).group(1)
            fn = f"{fam}-{hashlib.sha1(u.encode()).hexdigest()[:10]}.woff2"
            p = OUT / fn
            if not p.exists():
                p.write_bytes(get(u))
            total += p.stat().st_size
            return f"url(/assets/fonts/{fn})"
        css = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", repl, css)
        (OUT / f'{name}.css').write_text('/* Self-hosted web fonts, SIL Open Font License 1.1. Generated by tools/fetch_fonts.py */\n' + css)
        print(f'{name}.css: {css.count("@font-face")} faces')
    (OUT / 'LICENSE.txt').write_text('Geist and Geist Mono (Vercel), Fraunces (Undercase Type) and IBM Plex Sans Arabic (IBM) are\nlicensed under the SIL Open Font License 1.1: https://openfontlicense.org/\nFiles here are the subsets Google Fonts serves, downloaded by tools/fetch_fonts.py so that\ncookwala.ai pages make no request to a third party.\n')
    print(f'{total/1024:.0f} KB of woff2 in {OUT}')
if __name__ == '__main__':
    sys.exit(main())
